export const listItems = [
    {text: "All Departments", url: "/"},
    {text: "Alexa Skills", url: "/"},
    {text: "Amazon Devices", url: "/"},
    {text: "Amazon Fresh", url: "/"},
    {text: "Amazon Pharmacy", url: "/"},
    {text: "Amazon Warehouse", url: "/"},
    {text: "Apps & Games", url: "/"},
    {text: "Audible Books & Originals", url: "/"},
    {text: "Automotive", url: "/"},
    {text: "Beauty & Personal Care", url: "/"},
    {text: "Books", url: "/"},
    {text: "CDs & Vinyl", url: "/"},
    {text: "Cell Phones & Accessories", url: "/"},
    {text: "Clothing, Shoes & Jewelry", url: "/"},
    {text: "Collectible Coins", url: "/"},
]